[build]
  publish = "./"

# Remove .html extensions
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true

# Force HTTPS and non-www
[[redirects]]
  from = "http://www.ragadecode.com/*"
  to = "https://ragadecode.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ragadecode.com/*"
  to = "https://ragadecode.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ragadecode.com/*"
  to = "https://ragadecode.com/:splat"
  status = 301
  force = true
