[[redirects]]
  from = "/news-article/air-india-171-understanding-the-tragedy-and-the-possibility-of-vapor-lock"
  to = "/airlines/air-india-171-understanding-the-tragedy-and-the-possibility-of-vapor-lock"
  status = 301